# Generated by Django 5.2.8 on 2025-11-25 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metro', '0002_ticket_expires_at_purchaseotp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metroline',
            old_name='is_active',
            new_name='is_enabled',
        ),
        migrations.RemoveField(
            model_name='metroline',
            name='allow_ticket_purchase',
        ),
    ]
